export const SET_PAGE = 'SET_PAGE';

export const BOOKS_SUGGESTIONS_FIND_BY_QUERY = 'BOOKS_SUGGESTIONS_FIND_BY_QUERY';
export const BOOKS_SUGGESTIONS_FIND_BY_QUERY_PENDING = 'BOOKS_SUGGESTIONS_FIND_BY_QUERY_PENDING';
export const BOOKS_SUGGESTIONS_FIND_BY_QUERY_FULFILLED = 'BOOKS_SUGGESTIONS_FIND_BY_QUERY_FULFILLED';
export const BOOKS_SUGGESTIONS_FIND_BY_QUERY_REJECTED = 'BOOKS_SUGGESTIONS_FIND_BY_QUERY_REJECTED';

export const BOOKS_FIND_BY_QUERY = 'BOOKS_FIND_BY_QUERY';
export const BOOKS_FIND_BY_QUERY_PENDING = 'BOOKS_FIND_BY_QUERY_PENDING';
export const BOOKS_FIND_BY_QUERY_FULFILLED = 'BOOKS_FIND_BY_QUERY_FULFILLED';
export const BOOKS_FIND_BY_QUERY_REJECTED = 'BOOKS_FIND_BY_QUERY_REJECTED';

export const BOOKS_GET_BY_ID = 'BOOKS_GET_BY_ID';
export const BOOKS_GET_BY_ID_PENDING = 'BOOKS_GET_BY_ID_PENDING';
export const BOOKS_GET_BY_ID_FULFILLED = 'BOOKS_GET_BY_ID_FULFILLED';
export const BOOKS_GET_BY_ID_REJECTED = 'BOOKS_GET_BY_ID_REJECTED';
